### ISSUE TITLE
Notifications rework

### ISSUE THREAD

**Issue by ramonlsouza** [bigbluebutton/bigbluebutton#14725]
**Is your feature request related to a problem? Please describe.**
Currently each component that need to show notification has a different logic for it.
In general, the component tracks a Collection in mongodb. When something is changed it needs to compare with last version and decide if it is time to show a notification or not.

**Describe the solution you'd like**
Refactor all current notifications to use the new pattern (#14703) where all notifications are sent from akka-apps.

#### user join/left
- [x] UserJoinedMeeting (PR #14737 - akka-apps only)
- [x] UserLeftMeeting (PR #14737 - akka-apps only)

#### breakout rooms
- [x] BreakoutRoomEnded (PR #14728)
- [x] UserMessageToAllBreakouts (PR #14728)
- [x] BreakoutDurationUpdated - viewers (PR #14703)
- [x] BreakoutDurationUpdated - moderator (PR #14703)

#### recording
- [x] RecordingStarted (PR #14737 - akka-apps only)
- [x] RecordingStopped (PR #14737 - akka-apps only)

#### guest user
- [x] NewGuestUser (PR #14737 - akka-apps only)

#### lock settings
- [x] DisableCamLockSetting (PR #14737 - akka-apps only)
- [x] EnableCamLockSetting (PR #14737 - akka-apps only)
- [x] DisableMicLockSetting (PR #14737 - akka-apps only)
- [x] EnableMicLockSetting (PR #14737 - akka-apps only)
- [x] DisablePrivateChatLockSetting (PR #14737 - akka-apps only)
- [x] EnablePrivateChatLockSetting (PR #14737 - akka-apps only)
- [x] DisablePublicChatLockSetting (PR #14737 - akka-apps only)
- [x] EnablePublicChatLockSetting (PR #14737 - akka-apps only)
- [x] DisableNotesLockSetting (PR #14737 - akka-apps only)
- [x] EnableNotesLockSetting (PR #14737 - akka-apps only)
- [x] HideUserListLockSetting (PR #14737 - akka-apps only)
- [x] ShowUserListLockSetting (PR #14737 - akka-apps only)
- [x] OnlyModeratorWebcamDisabledLockSetting (PR #14737 - akka-apps only)
- [x] OnlyModeratorWebcamEnabledLockSetting (PR #14737 - akka-apps only)

#### mute/unmute
- [x] MeetingMuted (PR #14737 - akka-apps only)
- [x] MeetingUnmuted (PR #14737 - akka-apps only)

#### polls
- [x] HasPublishedPoll (PR #14737 - akka-apps only)

#### promote/demote
- [x] UserPromotedToModerator (PR #14737 - akka-apps only)
- [x] UserDemotedToViewer (PR #14737 - akka-apps only)

Thanks @JoVictorNunes for the [notification_list.pdf](https://github.com/bigbluebutton/bigbluebutton/files/8399382/notification_list.pdf)
