### ISSUE TITLE
v2.6 - Automated tests coverage

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#15456]
### **📈 Current coverage: 88,2% 📈**

_This issue contains a checklist of features and actions checked in case there is already an automated test for this. It can be updated over time. To check the current coverage, see the "task" part below the issue title._
___

### Actions bar 
<details>
<summary>Actions button</summary>

- Manage presentation
  - [x] Remove presentation
  - [x] Send presentation to chat - #15962
  - [x] Upload new presentation
  - [x] Remove presentation
  - [x] Upload and remove presentation with the same user
  - [x] Upload and remove presentation with another user - new presenter
- Start poll
  - [x] Starting a poll without a presentation should display a warning message - #15911
  - [x] Custom input - #15911
  - [x] Write the question
  - [x] Anonymous poll
  - [x] Quick poll (from the presentation)
  - [x] Add item
  - [x] Remove item
  - [x] Edit item
  - [x] Allow multiple choices - #15911
  - Publish poll
      - [x] On presentation
      - [x] On chat
  - Poll types
    - [x] True / false
    - [x] A / B / C / D
    - [x] Yes / no / abstention
    - [x] User Response
   - [x] Share an external video
   - [x] Select a random user
   - Layout setting modal
     - [x] Custom - #17811
     - [x] Smart layout - #17811
     - [x] Focus on presentation - #16540
     - [x] Focus on video - #16540
     - [ ] Propagate layout
     - [x] Push layout to all - #17811
</details>

<details>
  <summary>Center bar</summary>

- Audio
  - [x] Join the microphone
  - [x] Mute by microphone button
  - [x] Mute itself by talking indicator
  - [x] Mute another user by talking indicator
  - [ ] Select a different input device
  - [x] Listen only
- Webcam
  - [x] Start sharing webcam
  - [x] Stop sharing webcam - #15680
  - [x] Webcam content
  - [x] Webcam talking indicator
  - [ ] Mirror webcam
  - [x] Pinning and unpinning webcam - #15680
  - [x] Make fullscreen - #15680
  - Settings
    - [x] Change video quality - #15680
    - [ ] Change camera input device
    - [x] Select one of the default backgrounds - #15680
    - [x] Upload and apply a new background - #15680
    - [x] Remove an uploaded background - #15680
    - [x] Keep backgrounds uploaded when the user rejoins in a different tab - #15680
- [x] Share your screen

</details>

<details>
  <summary>Right bar :heavy_check_mark:</summary>

- [x] Minimize / restore presentation
- [x] Raise / lower hand
</details>

___

### Sidebar
<details>
  <summary>Chat</summary>

- [x] Character limit
- [x] Not able to send an empty message
- [ ] Show "More messages below" to scroll down the chat messages
- Emoji
  - [x] Send emoji on public chat
  - [x] Send emoji on private chat
  - [x] Copy chat with emoji
  - [x] Save chat with emoji
  - [ ] Select an emoji from the button
  - [x] Automatically insert an emoji by typing
- Public chat
  - [x] Send message
  - Chat options
    - [x] Save chat
    - [x] Copy chat
    - [x] Clear chat
- Private chat
  - [x] Send message
  - [x] Close chat
  - [x] Chat is disabled when the user leaves the meeting
</details>

<details>
  <summary>Shared notes :heavy_check_mark:</summary>

- [x] Edit shared notes
- [x] Edit shared notes with more than one user - #15958
- [x] See notes as a user without edit permission - #15958
- [x] Formate text - #15958
- [x] Export notes - #15958
- [x] Convert notes to presentation - #15958
</details>

<details>
  <summary>User list</summary>

- [x] Toggle user list
- User item
  - Tag name
    - [ ] Webcam indicator
    - [x] Mobile
    - [ ] Last room name label
  - Audio indicator
    - [ ] Unmuted
    - [ ] Muted
  - [x] Change user status
  - [x] Start private chat
  - [x] Give whiteboard access - #16125
  - [x] Remove whiteboard access - #16125
  - [x] Make presenter
  - [x] Take presenter
  - [x] Demote to viewer
  - [x] Promote to moderator
  - [x] Remove user - #16465
  - [x] Remove user (Prevent rejoining) - #16465
</details>

<details>
  <summary>Manage users</summary>

- [x] Mute all users - #16128
- [x] Mute all users except the presenter - #16128
- Lock viewers
  - [x] Share webcam
  - [x] See other viewers' webcams
  - [x] Share microphone
  - [x] Send Public chat messages
  - [x] Send Private chat messages
  - [x] Edit Shared Notes
  - [x] See other viewers in the Users list
  - [x] Unlock a user
- Guest policy
  - [x] Always accept
  - [x] Always deny
  - Ask moderator
    - [x] Message to the guests' lobby - #15818
    - [ ] Allow all authenticated
    - [x] Allow all guests - #15818
    - [x] Allow everyone - #15818
    - [x] Deny everyone - #15818
    - [x] Remember choice - #15818
    - Actions to a specific pending user
      - [x] Message - #15818
      - [x] Accept - #15818
      - [x] Deny - #15818
- [x] Save user names
- [ ] Clear all status icons
- Breakout rooms
  - Create
    - [x] Change the number of rooms
    - [x] Change duration time
    - [x] Randomly assign
    - [x] Reset assignments
    - [x] Remove a specific assignment
    - [x] Allow users to choose a breakout room to join
    - [x] Change room's name
    - [x] Drag and drop user into a room
  - After creating breakout rooms
    - [x] Ask to join
    - [x] Join room
    - [x] Join with Audio
    - [x] Message to all rooms
    - [x] Change duration time
    - [x] Invite a user after creating rooms
    - [x] User name shows below room's name
    - [x] Shows the "already on room" label
    - [x] Shows breakout room time remaining
    - [x] End all breakout rooms
- [x] Write closed captions - #16432
- Learning Dashboard - #16972 and #17200
  - [x] Show meeting status
  - [x] Show duration
  - [x] Download session data
  - [x] Timeline
  - Poll
    - [x] Poll count
    - [x] Poll votes by user
  - Overview
    - [x] Users' name
    - [x] Join time
    - [x] Leave time
    - [x] Online time
    - [x] Talk time
    - [x] Webcam time
    - [x] Messages
    - [x] Emojis
    - [x] Raise hands
    - [x] Activity scores (only for non-moderators)
    - [x] Current status
</details>

___

### Presentation
- [x] Make presentation fullscreen - #16046
- [x] Snapshot of the current presentation - #16046
- [x] Hide toolbars - #17675
- Presenter
  - Presentation toolbar
    - Center
      - [x] Previous slide
      - [x] Select slide - #17675
      - [x] Next slide 
    - Right
      - [x] Multi-user
      - [x] Zoom out
      - [x] Reset zoom - #17675
      - [x] Zoom in
      - [x] Fit to width
- Whiteboard
  - [x] Draw Line
  - [x] Erase
  - [x] Draw shape
  - [x] Draw arrow
  - [x] Type text
  - [x] Real-time text typing - #17533
  - [x] Sticky
  - [x] Delete - #17533
  - [x] Undo - #17533
  - [x] Redo - #17533
  - Options
    - [x] Color - #17533
    - [x] Fill - #17533
    - [x] Dash - #17533
    - [x] Size - #17533
    - [ ] Keep open
____
### Connection status :heavy_check_mark:
- [x] Show network data
- [x] Copy network data
- [x] Enable other participants' webcams
- [x] Enable desktop sharing
- [x] User reported with bad connection
___
### Options

- [ ] Make fullscreen
<details>
  <summary>Settings</summary>

- Application
  - [ ] Animations
  - [x] Dark mode - #16018
  - [x] Application language
  - [x] Font size - #16506
- Notifications
  - Audio alerts
    - [ ] Chat Message
    - [ ] User Join
    - [ ] User Leave
    - [ ] Raise hand
  - Popup alerts
    - [ ] Chat Message
    - [x] User Join
    - [ ] User Leave
    - [ ] Raise hand
- Data Savings
  - [ ] Enable other participants webcams
  - [ ] Enable desktop sharing
</details>

- [x] About
- [x] Help
- [x] Keyboard shortcuts
- [ ] End meeting
- [x] Leave the meeting
___
### CustomParameters
<details>
  <summary>Application parameters</summary>

- [x] userdata-bbb_ask_for_feedback_on_logout
- [x] userdata-bbb_auto_join_audio
- [x] userdata-bbb_client_title
- [x] userdata-bbb_force_listen_only
- [x] userdata-bbb_listen_only_mode
- [x] userdata-bbb_skip_check_audio
- [x] userdata-bbb_skip_check_audio_on_first_join
- [x] userdata-bbb_override_default_locale - #16673
</details>

<details>
  <summary>Branding parameters</summary>

- [x] userdata-bbb_display_branding_area
</details>

<details>
  <summary>Shortcut parameters</summary>

- [x] userdata-bbb_shortcuts
</details>

<details>
  <summary>Kurento parameters</summary>

- [x] userdata-bbb_auto_share_webcam
- [x] userdata-bbb_preferred_camera_profile - #16673
- [x] userdata-bbb_enable_screen_sharing
- [x] userdata-bbb_enable_video
- [ ] userdata-bbb_record_video
- [x] userdata-bbb_skip_video_preview
- [x] userdata-bbb_skip_video_preview_on_first_join
- [x] userdata-bbb_mirror_own_webcam
</details>

<details>
  <summary>Presentation parameters</summary>

- [x] userdata-bbb_force_restore_presentation_on_new_events
</details>

<details>
  <summary>Whiteboard parameters</summary>

- [x] userdata-bbb_multi_user_pen_only
- [x] userdata-bbb_presenter_tools
- [x] userdata-bbb_multi_user_tools
</details>

<details>
  <summary>Themeing & styling parameters</summary>

- [x] userdata-bbb_custom_style
- [x] userdata-bbb_custom_style_url
</details>

<details>
  <summary>Layout parameters</summary>

- <s>userdata-bbb_auto_swap_layout</s> - **Removed**
- <s>userdata-bbb_hide_presentation</s> - **Removed**
- [x] userdata-bbb_hide_presentation_on_join - #17928
- [x] userdata-bbb_show_participants_on_login
- [x] userdata-bbb_show_public_chat_on_login
- [x] userdata-bbb_hide_nav_bar - #16673
- [x] userdata-bbb_hide_actions_bar - #16673
</details>

<details>
  <summary>External parameters</summary>

- [x] userdata-bbb_outside_toggle_self_voice
- [x] userdata-bbb_outside_toggle_recording
</details>

___
### Notifications :heavy_check_mark:
  - [x] Save settings
  - [x] Save connection status settings
  - [x] Public chat
  - [x] Private chat
  - [x] Poll results
  - [x] Presentation upload
  - [x] Start screenshare

___
- [ ] Visual regression
- [ ] Metrics
- API
  - [x] GetMeetingInfo
  - [x] GetMeetings
  - [x] BreakoutWithoutParent
  - [x] BreakoutWithoutSequenceNumber
  - [x] BreakoutWithNonexistentParent
  - [x] BreakoutMeetingInfo

**Comment by antonbsa** [comment]
Closing it due to #18178
