### ISSUE TITLE
v2.7 - Automated tests coverage

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#18178]
_This issue contains a checklist of features and actions checked in case there is already an automated test for this. It can be updated over time. To check the current coverage, see the "task" part below the issue title._
___

### Actions bar 
<details>
<summary>Actions button</summary>

- Manage presentation
  - [x] Remove presentation
  - [ ] (!) Send presentation with annotation to chat
  - [ ] ** **New** ** - Enable original presentation download
  - [x] Upload new presentation
  - [x] Remove all presentations
  - [x] Upload and remove presentation with the same user
  - [x] Upload and remove presentation with another user - new presenter
- Start poll
  - [x] Starting a poll without a presentation should display a warning message
  - [x] Custom input
  - [x] Write the question
  - [x] Anonymous poll
  - [x] Quick poll (from the presentation)
  - [x] Add item
  - [x] Remove an item
  - [x] Edit item
  - [x] Allow multiple choices
  - Publish poll
      - [x] On presentation
      - [x] On chat
  - Poll types
    - [x] True / false
    - [x] A / B / C / D
    - [x] Yes / no / abstention
    - [x] User Response
   - [x] Share an external video
   - [x] Select a random user
   - Layout setting modal
     - [x] Custom
     - [x] Smart layout
     - [x] Focus on presentation
     - [x] Focus on video
     - [x] Propagate layout
     - [x] Keep pushing to everyone
</details>

<details>
  <summary>Center bar</summary>

- Audio
  - [x] Join the microphone
  - [x] Mute by microphone button
  - [x] Mute itself by talking indicator
  - [x] Mute another user by talking indicator
  - [ ] Select a different input device
  - [x] Listen only
- Webcam
  - [x] Start sharing webcam
  - [x] Stop sharing webcam
  - [x] Checks webcam content
  - [ ] ** **New** ** - Share camera as content
  - [ ] ** **New** ** - Disable self-view
  - [x] Webcam talking indicator
  - [ ] Mirror webcam
  - [x] Pinning and unpinning the webcam
  - [x] Make fullscreen
  - Settings
    - [x] Change video quality
    - [ ] Change camera input device
    - [ ] Change Brightness
    - [x] Select one of the default backgrounds
    - [x] Upload and apply a new background
    - [x] Remove an uploaded background
    - [x] Keep backgrounds uploaded when the user rejoins in a different tab
- [x] Share your screen
- [x] Raise / lower hand
  - [ ] (!) ** **New** ** - Add reaction
  - [ ] (!) ** **New** ** -  Set yourself as present
  - [ ] (!) ** **New** ** -  Set yourself as away

</details>

<details>
  <summary>Right bar :heavy_check_mark:</summary>

- [x] Minimize / restore presentation
</details>

___

### Sidebar
<details>
  <summary>Chat</summary>

- [x] Character limit
- [x] Not able to send an empty message
- [ ] Show "More messages below" to scroll down the chat messages
- Emoji
  - [x] Send emoji on public chat
  - [x] Send emoji on private chat
  - [x] Copy chat with emoji
  - [x] Save chat with emoji
  - [x] Select an emoji from the button
  - [x] Automatically insert an emoji by typing
- Public chat
  - [x] Send message
  - Chat options
    - [x] Save chat
    - [x] Copy chat
    - [x] Clear chat
- Private chat
  - [x] Send message
  - [x] Close chat
  - [x] Chat is disabled when the user leaves the meeting
</details>

<details>
  <summary>Shared notes :heavy_check_mark:</summary>

- [x] Edit shared notes
- [x] Edit shared notes with more than one user
- [x] See notes as a user without edit permission
- [x] Formate text
- [x] Export note
- [x] Convert notes to the presentation
- [x] Pin notes onto the whiteboard
</details>

<details>
  <summary>User list</summary>

- [x] Toggle user list
- User item
  - Tag name
    - [ ] Webcam indicator
    - [x] Mobile
    - [ ] Last room name label
  - Audio indicator
    - [ ] Unmuted
    - [ ] Muted
  - <s>Change user status</s>
  - [x] Give whiteboard access
  - [x] Remove whiteboard access
  - [x] Make presenter
  - [x] Take presenter
  - [x] Demote to viewer
  - [x] Promote to moderator
  - [x] Remove user
  - [x] Remove user (Prevent rejoining)
</details>

<details>
  <summary>Manage users</summary>

- [x] Mute all users
- [x] Mute all users except the presenter
- Lock viewers
  - [x] Share webcam
  - [x] See other viewers' webcams
  - [x] Share microphone
  - [x] Send Public chat messages
  - [x] Send Private chat messages
  - [x] Edit Shared Notes
  - [x] See other viewers in the Users list
  - [ ] See other viewers cursors
  - [ ] ** **New** ** - See other viewers annotations
  - [ ] Unlock a user for each lock setting option
- Guest policy
  - [x] Always accept
  - [x] Always deny
  - Ask moderator
    - [x] Message to the guests' lobby
    - [ ] Allow all authenticated
    - [x] Allow all guests
    - [x] Allow everyone
    - [x] Deny everyone
    - [x] Remember the choice
    - Actions to a specific pending user
      - [x] Message
      - [x] Accept
      - [x] Deny
- [x] Save user names
- [ ] (!) Clear all status icons
- Breakout rooms
  - Create
    - [x] Change the number of rooms
    - [x] Change duration time
    - [x] Randomly assign
    - [x] Reset assignments
    - [x] Remove a specific assignment
    - [x] Allow users to choose a breakout room to join
    - [x] Change the room's name
    - [x] Drag and drop the user into a room
  - After creating breakout rooms
    - [x] Ask to join
    - [x] Join room
    - [x] Join with Audio
    - [x] Message to all rooms
    - [x] Change duration time
    - [x] Invite a user after creating rooms
    - [x] User name shows below room's name
    - [x] Shows the "already on room" label
    - [x] Shows breakout room time remaining
    - [x] End all breakout rooms
- [x] Write closed captions
- Learning Dashboard
  - [x] Show meeting status
  - [x] Show duration
  - [x] Download session data
  - [x] Timeline
  - Poll
    - [x] Poll count
    - [x] Poll votes by user
  - Overview
    - [x] Users' names
    - [x] Join time
    - [x] Leave time
    - [x] Online time
    - [x] Talk time
    - [x] Webcam time
    - [x] Messages
    - [x] Emojis
    - [x] Raise hands
    - [x] Activity scores (only for non-moderators)
    - [x] Current status
</details>

___

### Presentation
- [x] Make presentation fullscreen
- [x] Snapshot of the current presentation
- [ ] Hide toolbars
- Presenter
  - Presentation toolbar
    - Center
      - [x] Previous slide
      - [x] Select slide
      - [x] Next slide
    - Right
      - [x] Multi-user
      - [x] Zoom out
      - [x] Reset zoom
      - [x] Zoom in
      - [x] Fit to width
- Whiteboard
  - [x] Draw Line
  - [x] Erase
  - [x] Draw shape
  - [x] Draw arrow
  - [x] Type text
  - [x] Real-time text typing
  - [x] Sticky
  - [x] Delete a drawing
  - [x] Change styles
  - [x] Undo
  - [x] Redo
  - [x] Clear
  - TlDraw style options
    - [x] Color
    - [x] Fill
    - [x] Dash
    - [x] Size
    - [ ] Keep open
  - TlDraw shape options
   - [ ] Duplicate
   - [ ] Rotate
   - [ ] Unlock
   - [ ] Unlock aspect ratio
   - [ ] Group
   - [ ] Move to back
   - [ ] Move backward
   - [ ] Move forward
   - [ ] Move to front
   - [ ] Reset angle
   - [ ] Align left
   - [ ] Align horizontal center
   - [ ] Align right
   - [ ] Strech horizontal
   - [ ] Distribute horizontal
   - [ ] Align top
   - [ ] Align vertical center
   - [ ] Align bottom
   - [ ] Stretch vertical
   - [ ] Distribute vertical
____
### Connection status :heavy_check_mark:
- [x] Show network data
- [x] Copy network data
- [x] Enable other participants' webcams
- [x] Enable desktop sharing
- [x] User reported with bad connection
___
### Options

- [ ] Fullscreen application
<details>
  <summary>Settings</summary>

- Application
  - [ ] Animations
  - [x] Dark mode
  - [ ] Auto hide whiteboard toolbars
  - [ ] ** **New** ** - Disable self-view
  - [x] Application language
  - [x] Font size
- Notifications
  - Audio alerts
    - [ ] Chat Message
    - [ ] User Join
    - [ ] User Leave
  - Popup alerts
    - [ ] Chat Message
    - [x] User Join
    - [ ] User Leave
- Data Savings
  - [ ] Enable other participants webcams
  - [ ] Enable other participants desktop sharing
</details>

- [x] About
- [x] Help
- [x] Keyboard shortcuts
- [ ] End meeting
- [x] Leave the meeting
___
### CustomParameters _(requires update)_
<details>
  <summary>Application parameters</summary>

- [x] userdata-bbb_ask_for_feedback_on_logout
- [x] userdata-bbb_auto_join_audio
- [x] userdata-bbb_client_title
- [x] userdata-bbb_force_listen_only
- [x] userdata-bbb_listen_only_mode
- [x] userdata-bbb_skip_check_audio
- [x] userdata-bbb_skip_check_audio_on_first_join
- [x] userdata-bbb_override_default_locale - #16673
</details>

<details>
  <summary>Branding parameters</summary>

- [x] userdata-bbb_display_branding_area
</details>

<details>
  <summary>Shortcut parameters</summary>

- [x] userdata-bbb_shortcuts
</details>

<details>
  <summary>Kurento parameters</summary>

- [x] userdata-bbb_auto_share_webcam
- [x] userdata-bbb_preferred_camera_profile - #16673
- [x] userdata-bbb_enable_screen_sharing
- [x] userdata-bbb_enable_video
- [ ] userdata-bbb_record_video
- [x] userdata-bbb_skip_video_preview
- [x] userdata-bbb_skip_video_preview_on_first_join
- [x] userdata-bbb_mirror_own_webcam
</details>

<details>
  <summary>Presentation parameters</summary>

- [x] userdata-bbb_force_restore_presentation_on_new_events
</details>

<details>
  <summary>Whiteboard parameters</summary>

- [x] userdata-bbb_multi_user_pen_only
- [x] userdata-bbb_presenter_tools
- [x] userdata-bbb_multi_user_tools
</details>

<details>
  <summary>Themeing & styling parameters</summary>

- [x] userdata-bbb_custom_style
- [x] userdata-bbb_custom_style_url
</details>

<details>
  <summary>Layout parameters</summary>

- [x] userdata-bbb_auto_swap_layout
- [x] userdata-bbb_hide_presentation
- [x] userdata-bbb_show_participants_on_login
- [x] userdata-bbb_show_public_chat_on_login
- [x] userdata-bbb_hide_nav_bar - #16673
- [x] userdata-bbb_hide_actions_bar - #16673
</details>

<details>
  <summary>External parameters</summary>

- [x] userdata-bbb_outside_toggle_self_voice
- [x] userdata-bbb_outside_toggle_recording
</details>

___
### Notifications :heavy_check_mark:
  - [x] Save settings
  - [x] Save connection status settings
  - [x] Public chat
  - [x] Private chat
  - [x] Poll results
  - [x] Presentation upload
  - [x] Start screenshare

___

### API calls
  - [ ] Create
  - [ ] Join as moderator
  - [ ] Join as attendee
  - [ ] IsMettingRunning
  - [x] GetMeetingInfo
  - [ ] End
  - [x] GetMeetings
  - [ ] GetDefaultConfigXML
  - [ ] SetConfigXML
  - [ ] Enter
  - [ ] ConfigXML
  - [ ] SignOut
  - Recording
    - [ ] GetRecordings
    - [ ] PublishRecordings
    - [ ] DeleteRecordings
    - [ ] UpdateRecordings
    - [ ] GetRecordingTextTracks
  - Mobile
    - [ ] Join as moderator
    - [ ] Join as attendee 
  - Breakout
    - [x] BreakoutWithoutParent
    - [x] BreakoutWithoutSequenceNumber
    - [x] BreakoutWithNonexistentParent
    - [x] BreakoutMeetingInfo

___

- Visual regression
- Metrics
