### ISSUE TITLE
[meta] Integration of LiveKit into BigBlueButton

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#21059]
# Integration of LiveKit into BigBlueButton

**This is a meta issue to track the integration of the LiveKit framework into BigBlueButton.**

The goal is to have a centralized view of the process. Specific issues regarding the implementation will be opened as needed and associated with this one. This is a living document and subject to changes and suggestions.

1. [Rationale](#rationale)
2. [Integration](#integration)
   - [Phase 1: Integrate LiveKit as an Experimental Feature](#1-integrate-livekit-into-the-bbb-stack-as-an-experimental-feature)
     - [Tentative Server Architecture, First Phase](#tentative-server-architecture-first-phase)
     - [Feature Parity Tracking (Annex)](#feature-parity-tracking)
   - [Phase 2: Set LiveKit as the Default Media Stack](#2-set-livekit-as-the-default-media-stack)
   - [Phase 3: Remove the Old Media Stack](#3-remove-the-old-media-stack)
3. [Annex 1: Feature Parity Tracking](#annex-feature-parity-tracking)
4. [Annex 2: Known Issues](#annex-2-known-issues)
5. [Annex 3: Notes](#annex-3-notes)
6. [Annex 4: CHANGELOG](#annex-4-changelog)

## Rationale

While our current media stack works, it has several pain points that need to be addressed (not extensive):

- **Isolated WebRTC transports and mixed RTP topology:** 
  - Unreliable lip-syncing 
  - Improper stream prioritization.
- **Audio quality/reliability:**
  - The MCU part (FreeSWITCH) introduces undesirable audio artifacts and sync issues, which are hard to fix.
  - Missing newer developments like RED, though this is easier to address.
- **Lack of support for simulcast/SVC and H.264/VP9/AV1.**
- **Relying on ICE lite causes issues with Firefox, which is incompatible with ICE lite.**

For developers, the current stack presents challenges:

- **Two media servers (FreeSWITCH and mediasoup) and mixed RTP topology (MCU + SFU):**
  - Harder to maintain; an unified approach is the proper design
- **Loads of custom code:**
  - Stems from an era without good open-source frameworks, which is no longer the case.
- **Poor documentation, unformalized signaling protocol:**
  - Requires "reverse engineering" to understand.
- **Client-side WebRTC code structure:**
  - Not reusable as an SDK, leading to re-implementations when new clients are needed [[1]](https://github.com/mconf/bbb-mobile-sdk)[[2]](https://github.com/bennyboer/bbb_app).

This leads us to [LiveKit](https://livekit.io/), an open-source RTC framework that addresses many of the aforementioned issues.

## Integration

The solution is to integrate LiveKit into BigBlueButton in phases:

### 1. Integrate LiveKit into the BBB stack as an experimental feature

This will allow us to test the waters and see how it behaves in a real environment. 
The goal is to avoid impacting the default setup and to make it easily toggled 
on/off on a per-server or per-meeting basis.

This is the same strategy that was used to integrate mediasoup into BBB. We'll
avoid burning bridges until this first phase is deemed production grade. Do not
expect any of the default media stack to be removed at this point - neither any
large refactors that would impact it.

**Criteria for advancing to the next phase:**
- Achieve feature parity in [**Audio**](#annex-feature-parity-tracking-audio), [**Video**](#annex-feature-parity-tracking-video), and [**Screen sharing**](#annex-feature-parity-tracking-screen-sharing) with the current media stack.
- Production-grade quality.
- Minimal disruption to end users and administrators

**Feature parity progress** (see detailed tracking in [Annex: Feature Parity Tracking](#annex-feature-parity-tracking)):
- Audio: In progress.
- Video: In progress.
- Screen sharing: In progress.

**We will avoid removing the default media stack until this phase is production-ready.**

#### 1.1 Tentative server architecture, first phase

The diagram below outlines the tentative server architecture for the first phase. New components will likely not be installed by default until production-grade:

- **livekit-server:**
  - The livekit-server application itself, packaged by BBB.
  - An equivalent to the union of bbb-webrtc-sfu, mediasoup, bbb-fsesl-akka and FreeSWITCH
  - Runs inside the BBB node by default, can also run on an external node.
  - [x] ~`/create`: `livekitCredentials: { url, secret }` (encrypted payload).~
  - [x] webrtc-sfu module: token generation, permission handling, webhooks receiver, egress orchestration.
- **livekit-egress:**
  - Livekit's `egress` application, packaged by BBB
  - An equivalent to `bbb-webrtc-recorder`.
  - Runs alongside BBB.
  - [x] Track recording for A/V.
- **Tentatively obsoleted components:**
  - Marked for removal in phases 2 and 3.

![Tentative Server Architecture](https://github.com/user-attachments/assets/76a8bc5b-8cee-458b-b1c1-da53956ae575)

### 2. Set LiveKit as the default media stack

Once the first phase reaches production grade, LiveKit will be set as the default media stack.

**Goals for this phase:**
- [ ] Update and refine documentation for users and developers.
- [ ] Begin the deprecation process for the current media stack, including issuing deprecation notices.

### 3. Remove the old media stack

After LiveKit becomes the default media stack, the old media stack will be removed to simplify the codebase.

**Goals for this phase:**
- [ ] Complete removal of the old media stack.
- [ ] Refactor the codebase to align better with LiveKit’s architecture.
- [ ] Ensure all documentation is updated to reflect the changes.

### Feature parity tracking: audio

| **Features**                          | **Status**           | **Issues** | **PRs** |
| ------------------------------------- | -------------------- | ---------- | ------- |
| **Sharing**                           | Done                 |            | #21374  | 
| **Recording**                         | Done                 |            | #21374, #21961  |
| **Dial-in (SIP) integration**         | Done                 |            | #21374  |
| **Client-side Transcription**         | Done                 |            | #21374  |
| **Server-side Transcription**         | Done                 |            | https://github.com/bigbluebutton/bbb-livekit-stt/         |
| **I/O device control**                | Done                 |            | #21374  |
| **Share lock setting**                | Done                 |            | #21374  |
| **Breakout room audio-only transfer** | On hold              | https://github.com/bigbluebutton/bigbluebutton/issues/24546           |         |
| **Moderator mute control**            | Done                 |            | #21374  |
| **Autoplay handling**                 | Done                 |            | #21374  |
| **muteOnStart**                       | Done                 |            | #21374  |
| **Connection status data**            | Done                 |            | #22140  |
| **Speaking-while-muted alert**        | Done                 |            | #21374  |
| **Help modals**                       | Done                 |            | #21374  |
| **Filters**                           | Done                 |            | #21374  |
| **Audio floor mechanism**             | Done                 |            | #22247  |

### Feature parity tracking: video

| **Features**                       | **Status**  | **Issues** | **PRs** |
| ---------------------------------- | ----------- | ---------- | ------- |
| **Sharing**                        | Done        |            | #21374  |
| **Recording**                      | Done        |            | #21374  |
| **Pin**                            | Done        |            | #21374  |
| **Virtual backgrounds**            | Done        |            | #21374  |
| **Multiple cameras**               | Done        |            | #21374  |
| **Camera as content**              | Done        |            | #21374  |
| **Quality profiles**               | Done        |            |         |
| **Share lock setting**             | Done        |            | #21374  |
| **See other viewers lock setting** | Done        |            | #21374  |
| **Pagination**                     | Done        |            | #21374  |
| **Grid view**                      | Done        |            | #21374  |
| **Data savings**                   | Done        |            | #21374  |
| **Connection status data**         | Done        |            | #22140  |
| **Close cameras (moderators)**     | Done        |            | #21975  |
| **Disable self-view**              | Done        |            | #21374  |
| **Recording: support H.264, VP9 and AV1**              | TODO        |            |   |

### Feature parity tracking: screen sharing

| **Features**               | **Status**  | **Issues** | **PRs** |
| -------------------------- | ----------- | ---------- | ------- |
| **Sharing**                | Done        |            | #21374  |
| **Sharing A/V**            | Done        |            | #21374  |
| **Recording**              | Done        |            | #21374, #21961, #23015  |
| **Presenter-locked**       | Done        |            | #21374  |
| **Data savings**           | Done        |            | #21374  |
| **Connection status data** | Done        |            | #22140  |

## Annex 2: Known Issues

- [x] 3.0-beta.6: Screenshare end sound is playing whenever any mic track is unpublished (#21849)
- [ ] 3.0-beta.6: Audio lock setting is not being fully enforced (details - internal - prlanzarin)
- [x] 3.0-beta.6: Talking indicators may get stuck on user disconnection/re-connection
- [x] 3.0-beta.6: Shared camera may get stuck on for other users when the sharer disconnects/re-connects
- [x] 3.0-beta.6: Screen share state may become inconsistent after a presenter switch (meeting wide)
- [x] 3.0-beta.6: LK signal re-connection may get stuck on a loop when a user re-connects the client (side effect: unable to hear/see)
- [ ] 3.0-beta.6: Subscribing to specific audio streams sometimes fail silently (i.e.: user Y hears X, but not W)
  * Pending: selective subscription component has not been integrated in v3.0.x-release yet
- [x] 3.0-beta.6: Switching audio input devices might re-publish a track and change the client's mute state (https://github.com/bigbluebutton/bigbluebutton/issues/22071)
- [x] 3.0-beta.6: Autoplay handling modal sometimes not shown (side effects: unable to hear room unless gUM perm is given/mic is shared)
- [x] "Leave audio" is a no-op (under UI/UX review)
  * [x] Breakout rooms: absence of "leave audio" means the user stays connected in the main room
  * [x] Breakout rooms: main room user might stay unmuted when joining a breakout
- [ ] 3.0-rc.1: Token expiry is not handled
- [x] 3.0-rc.1: `recordFullDurationMedia=false` is unreliable when using LiveKit
- [ ] 3.0-rc.1: dial-in integration lacks documentation
- [x] 3.0-rc.1: egress lacks a proper build/bbb-conf orchestration
- [ ] 3.0-rc.2: connection status is aggregating duplicate up/down bitrate info (i.e.: showing more than what's being transmitted)

## Annex 3: Notes

- [ ] https://github.com/bigbluebutton/bigbluebutton/pull/21804 - Danimo: `We need to harden this before the release, checking hashes of downloaded artifacts.`
- [ ] Add livekit-sip to bigbluebutton.target when time comes
  - See https://github.com/bigbluebutton/bigbluebutton/issues/23247 (May 23 2025)

## Annex 4: CHANGELOG

- 02/10/24: updated the architecture diagram to include SIP/dial-in and live transcription components
- 08/10/24: added **Issues** and **PRs** columns to "Feature parity tracking" tables
- 27/11/24: update feature parity tables as of #21374
- 08/12/24: added `Annex 3: Notes`
- 11/12/24: added `Annex 2: Known Issues`
- 09/05/24: dial-in integration set to `Under Review` as its being slightly reworked

**Comment by Pierre-Lannoy** [comment]
OK. I know everything is not fully implemented / operational. I know it is marked as "experimental". I know all that…
I've just wanted to thank all contributors who work on this. It is a real game changer for me.
THANKS ❤

**Comment by ffdixon** [comment]
Appreciate the feedback @Pierre-Lannoy -- it's a marathon that we can see the finish line.

**Comment by Thyroxine** [comment]
Will this new stack allow dialing from hardware SIP video devices, as requested in #9579 ?

**Comment by prlanzarin** [comment]
> Will this new stack allow dialing into the BBB using SIP hardware video devices as requested in [#9579](https://github.com/bigbluebutton/bigbluebutton/issues/9579)? It seems that `livekit-sip` in the image looks like a possible solution.
@Thyroxine 
While we're serving and suporting livekit-sip, the application itself is not capable of doing video yet. So that won't be provided out of the box.

**Comment by pielonet** [comment]
Hi,

Any news on livekit --complete-- availability in BBB 3.0.X ?

Kind regards,
Thierry

**Comment by hex-m** [comment]
LiveKit is [experimental in 3.0](https://docs.bigbluebutton.org/3.0/new-features/#integration-with-livekit) and this usually doesn't change during one release. So the question would be what is the likelihood that LiveKit will be declared stable (or even used by default) in 3.1.

Relevant FAQ: https://docs.bigbluebutton.org/support/faq/#when-will-feature-x-be-implemented

**Comment by Ithanil** [comment]
I don't know the answer to that question, but I can guarantee that LiveKit is already used productively in significant BBB 3.0 deployments.

**Comment by Ithanil** [comment]
> Hi,
> 
> Any news on livekit --complete-- availability in BBB 3.0.X ?
> 
> Kind regards, Thierry

What feature are you missing? There is a solution to everything including dialin, besides this odd exception: https://github.com/bigbluebutton/bigbluebutton/issues/24546

**Comment by nathanael-h** [comment]
Hello, the company where I work is using livelit in production for one year, around 100 people.

By the way, I am working on this audio to-do from initial list : "Server-side Transcription" to have live caption from a self hosted speech to text tool. I might open a draft PR. Is there any  PR or issue about this specific topic?

**Comment by gschwienbacher** [comment]
> Hello, the company where I work is using livelit in production for one year, around 100 people.
> 
> By the way, I am working on this audio to-do from initial list : "Server-side Transcription" to have live caption from a self hosted speech to text tool. I might open a draft PR.

hello @nathanael-h - just out of curiosity: is the solution you are working on similar to this approach (besides Gladia)? https://github.com/bigbluebutton/bbb-livekit-stt/

**Comment by nathanael-h** [comment]
Hello @gschwienbacher yes it is very similar. I missed this dedicated BBB Live kit stt repo 😅 So what do you think I contribute to it so that it supports also openai compatible API? I plan to selfhost peaches  with faster whisper. speaches.ai/

**Comment by prlanzarin** [comment]
@nathanael-h Thanks for the PR against bbb-livekit-stt. While it's not part of the BBB docs yet, it is the transcription engine to be used with LiveKit in BBB - so your approach is correct.
Please ping me in the PR when it's ready for review.

**Comment by tsahilevi** [comment]
I figured I'd raise something here.

We've been working on [rtcstats](https://github.com/rtcstats/rtcstats) - client-side WebRTC stats collection that captures getStats() data (codec selection, bitrate, packet loss, jitter, resolution changes) from the browser in real time. It could give you actual numbers when comparing SFU backends during the migration, instead of relying on visual inspection.

Happy to help if this is useful. Full disclosure: I'm one of the people behind rtcStats.

**Comment by prlanzarin** [comment]
@tsahilevi certainly useful. We have some "in house" stats logging on our side, but it's
way simpler/more limited than what rtcstats does. It has been on my radar to look into rtcstats for a while now, maybe this is an incentive to do it sooner :).

I'll reach out if necessary!
